#!/usr/bin/env python
import sys
from marketing_posts.crew import MarketingPostsCrew

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Table,
    TableStyle,
    Image
)

from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors

import matplotlib.pyplot as plt


# ==============================
# STYLES
# ==============================

styles = getSampleStyleSheet()

title_style = ParagraphStyle(
    "TitleStyle",
    parent=styles["Title"],
    fontSize=36,
    leading=42,
    textColor=colors.HexColor("#1f4e79"),
    alignment=1,
    spaceAfter=40
)

heading_style = ParagraphStyle(
    "HeadingStyle",
    parent=styles["Heading2"],
    fontSize=22,
    textColor=colors.HexColor("#1f4e79"),
    spaceBefore=20,
    spaceAfter=10
)

body_style = ParagraphStyle(
    "BodyStyle",
    parent=styles["BodyText"],
    fontSize=12,
    leading=18
)


# ==============================
# DIVIDER LINE
# ==============================

def divider():
    t = Table([[""]], colWidths=[500])
    t.setStyle(TableStyle([
        ("LINEBELOW",(0,0),(-1,-1),1,colors.HexColor("#cccccc"))
    ]))
    return t


# ==============================
# HEADER + FOOTER
# ==============================

def page_design(canvas, doc):

    canvas.setFont("Helvetica-Bold",9)

    canvas.setFillColor(colors.HexColor("#1f4e79"))
    canvas.drawString(40,750,"AI Marketing Intelligence Report")

    canvas.setFillColor(colors.grey)

    page_num = canvas.getPageNumber()

    canvas.drawRightString(550,20,f"Page {page_num}")

    canvas.drawString(
        40,
        20,
        "Generated by AI Multi-Agent Marketing System"
    )


# ==============================
# EXTRACT COMPETITORS
# ==============================

def extract_market_insights(text):

    competitors = []
    keywords = ["Copilot","ChatGPT","Cursor","Codeium","Tabnine"]

    for k in keywords:
        if k.lower() in text.lower():
            competitors.append(k)

    if not competitors:
        competitors = ["GitHub Copilot","Cursor","Codeium"]

    return list(set(competitors))


# ==============================
# CHART
# ==============================

def create_chart(competitors):

    popularity = [80 - i*10 for i in range(len(competitors))]

    plt.figure(figsize=(8,4))

    bars = plt.bar(
        competitors,
        popularity,
        color="#1f4e79"
    )

    plt.title("AI Coding Assistant Market Presence", fontsize=14)

    plt.ylabel("Popularity Score")

    for bar in bars:

        height = bar.get_height()

        plt.text(
            bar.get_x()+bar.get_width()/2,
            height+1,
            str(height),
            ha="center"
        )

    plt.grid(axis="y",linestyle="--",alpha=0.4)

    plt.tight_layout()

    plt.savefig("competitor_chart.png")

    plt.close()


# ==============================
# CLEAN AI OUTPUT
# ==============================

def clean_ai_output(result):

    lines = []

    for line in result.split("\n"):

        line = line.strip()

        if not line or line.startswith("Here is"):
            continue

        # Remove markdown formatting
        line = line.replace("**","")
        line = line.replace("###","")
        line = line.replace("##","")
        line = line.replace("#","")

        lines.append(line)

    return lines


# ==============================
# GENERATE PDF
# ==============================

def generate_pdf(result,domain,description):

    competitors = extract_market_insights(result)

    create_chart(competitors)

    elements = []

    # COVER PAGE

    elements.append(Paragraph("AI Marketing", title_style))
    elements.append(Paragraph("Intelligence Report", title_style))
    elements.append(Spacer(1,30))

    elements.append(
        Paragraph(
            f"<b>Company:</b> {domain}",
            body_style
        )
    )

    elements.append(
        Paragraph(
            f"<b>Product:</b> {description}",
            body_style
        )
    )

    elements.append(Spacer(1,60))

    elements.append(
        Paragraph(
            "<font color='#777777'>Generated by AI Multi-Agent Marketing System</font>",
            body_style
        )
    )

    elements.append(PageBreak())


    # EXECUTIVE SUMMARY

    elements.append(Paragraph("Executive Summary", heading_style))
    elements.append(divider())

    elements.append(
        Paragraph(
            "This report was generated using an AI multi-agent system "
            "that performs automated research, competitor analysis "
            "and marketing strategy planning.",
            body_style
        )
    )


    # MARKET INTELLIGENCE

    elements.append(Paragraph("Market Intelligence", heading_style))
    elements.append(divider())

    elements.append(
        Paragraph(
            "AI developer tools are transforming the software industry. "
            "Organizations increasingly rely on AI assistants to "
            "accelerate development cycles and improve productivity.",
            body_style
        )
    )


    # COMPETITOR TABLE

    elements.append(Paragraph("Competitor Landscape", heading_style))
    elements.append(divider())

    data = [["Competitor","Category"]]

    for comp in competitors:
        data.append([comp,"AI Coding Assistant"])

    table = Table(data,colWidths=[250,200])

    table.setStyle(
        TableStyle([
            ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#1f4e79")),
            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
            ("FONTSIZE",(0,0),(-1,0),12),

            ("ROWBACKGROUNDS",(0,1),(-1,-1),
             [colors.whitesmoke, colors.lightgrey]),

            ("GRID",(0,0),(-1,-1),0.5,colors.grey),
            ("ALIGN",(0,0),(-1,-1),"CENTER")
        ])
    )

    elements.append(table)


    # CHART

    elements.append(Paragraph("Market Comparison", heading_style))
    elements.append(divider())

    elements.append(
        Image(
            "competitor_chart.png",
            width=440,
            height=240
        )
    )


    # TARGET AUDIENCE

    elements.append(Paragraph("Target Audience", heading_style))
    elements.append(divider())

    elements.append(
        Paragraph(
            "Primary users include developers, startups, engineering teams "
            "and technology companies looking to improve development "
            "productivity using AI coding assistants.",
            body_style
        )
    )


    # MARKETING STRATEGY

    elements.append(Paragraph("Marketing Strategy", heading_style))
    elements.append(divider())

    elements.append(
        Paragraph(
            "Recommended marketing channels include developer communities "
            "such as GitHub, StackOverflow, Hacker News, Reddit and "
            "technical blogs.",
            body_style
        )
    )

    elements.append(PageBreak())


    # CAMPAIGN IDEAS

    elements.append(Paragraph("AI Generated Campaign Ideas", heading_style))
    elements.append(divider())

    clean_lines = clean_ai_output(result)

    for line in clean_lines:

        # Make Month titles bold
        if line.lower().startswith("month"):
            elements.append(
                Paragraph(f"<b>{line}</b>", body_style)
            )
        else:
            elements.append(
                Paragraph(line, body_style)
            )

        elements.append(Spacer(1,6))


    # FINAL INSIGHTS

    elements.append(PageBreak())

    elements.append(Paragraph("Strategic Insights", heading_style))
    elements.append(divider())

    insights = [
        "AI coding assistants are one of the fastest growing developer tools.",
        "GitHub Copilot currently dominates the AI coding assistant market.",
        "Developer communities are the most effective marketing channel.",
        "AI productivity tools will expand rapidly in enterprise development."
    ]

    for i in insights:

        elements.append(
            Paragraph(f"<font color='#1f4e79'><b>• {i}</b></font>",body_style)
        )

        elements.append(Spacer(1,10))


    doc = SimpleDocTemplate(
        "marketing_report.pdf",
        pagesize=letter
    )

    doc.build(
        elements,
        onLaterPages=page_design
    )

    print("\nAdvanced marketing intelligence report generated: marketing_report.pdf")


# ==============================
# RUN
# ==============================

def run():

    print("===== AI MARKETING STRATEGY GENERATOR =====")

    domain = input("Enter company domain: ")
    description = input("Describe the project/product: ")

    inputs = {
        "customer_domain": domain,
        "project_description": description
    }

    print("\n===== STARTING CREW =====\n")

    crew = MarketingPostsCrew().crew()

    result = crew.kickoff(inputs=inputs)

    print("\n===== FINAL RESULT =====\n")

    print(result)

    generate_pdf(str(result),domain,description)


if __name__ == "__main__":
    run()